# DATA
data_path: data/

# DATASETS

# MODELS
model_path: models/

# CHECKPOINTS
temp_checkpoint_path: temp_checkpoints/

# RESULTS
results_path: results/

# LOGGING
logging_path: logs/
logging_level: debug

# API KEYS
openaq_api_key: fa7fb3574dffa89fac565317f05c87f007f5418c958af18ccd7a29810e7fffd0
ihme_api_key: 0u71itrqlwvjl68wuf81rvbeoeq297zt
